version: "3"

services:

  service-rocket-chat:
    environment:
      MONGO_URL: mongodb://mongodb:27017/rocketchat
      PORT: '3000'
      ROOT_URL: http://yourhost:3000
      MONGO_OPLOG_URL: ''
    labels:
      io.rancher.sidekicks: mongodb
      io.rancher.container.pull_image: always
    tty: true
    command:
    - node
    - main.js
    image: stefan125/sofia-service-rocket-chat:master
    stdin_open: true
  osgi-visualization-ui:
    labels:
      io.rancher.container.pull_image: always
    tty: true
    image: stefan125/sofia-service-osgi-visualization-ui:master
    stdin_open: true
  question-service:
    labels:
      io.rancher.container.pull_image: always
    tty: true
    image: stefan125/sofia-service-question:master
    networks:
      - sofianet
    stdin_open: true
  service-answer:
    labels:
      io.rancher.container.pull_image: always
    tty: true
    image: stefan125/sofia-service-answer:master
    networks:
      - sofianet
    stdin_open: true
  mongodb:
    labels:
      io.rancher.container.pull_image: always
    tty: true
    command:
    - mongod
    - --smallfiles
    - --oplogSize
    - '128'
    image: mongo:3.4
    stdin_open: true
  hubot-service:
    labels:
      io.rancher.container.pull_image: always
    tty: true
    image: stefan125/sofia-service-hubot:master
    networks:
      - sofianet
      - chatnet
    stdin_open: true
  wamp-router:
    networks:
      - sofianet
    ports:
      - 8090:8080/tcp
    labels:
      io.rancher.container.pull_image: always
    tty: true
    image: crossbario/crossbar
    stdin_open: true
  rocketchat-service:
    environment:
      ROCKETCHAT_PASSWORD: Uhupalere452
    labels:
      io.rancher.container.pull_image: always
    tty: true
    image: rocketchat/rocket.chat:latest
    stdin_open: true
    networks:
      - chatnet

networks:
  sofianet:
  chatnet:
